# Generated by Django 5.1.1 on 2024-09-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('ABANDONED', 'Abandoned'), ('CANCELED', 'Canceled'), ('NOT_STARTED', 'Not Started')], default='IN_PROGRESS', max_length=20),
        ),
    ]
